# Generated by Django 5.2 on 2025-09-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostsPostPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_mode', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('post_content', models.TextField()),
                ('colorProfilePost', models.CharField(default='#FFFFFF', max_length=7)),
                ('Profile', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
