# Generated by Django 5.2 on 2025-09-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postspostpage',
            name='account_mode',
            field=models.CharField(choices=[('reader', 'Reader'), ('writer', 'Writer'), ('poet', 'Poet')], max_length=30),
        ),
    ]
