# Generated by Django 5.2 on 2025-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_postspostpage_account_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='postspostpage',
            name='post_title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
