# Generated by Django 5.2.6 on 2025-09-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_postspostpage_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postspostpage',
            name='Profile',
        ),
        migrations.AddField(
            model_name='postspostpage',
            name='Profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
